matrix:
  include:
    - os: linux
      env: OS=linux
      sudo: required
    - os: linux
      env: OS=linux-cross CROSS=1
      # QEMU on Ubuntu precise is too old to run tests.
      # It doesn't fake /proc/self/maps.
      dist: trusty
      sudo: required
    - os: osx
      env: OS=osx
language: c
before_install:
  - if [[ "$OS" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$OS" == "linux" ]]; then sudo apt-get install gcc-multilib; fi
  - if [[ "$OS" == "linux-cross" ]]; then sudo apt-get update -qq; fi
  - if [[ "$OS" == "linux-cross" ]]; then sudo apt-get install qemu-user gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf; fi
script:
  - cd test && make check CROSS=$CROSS
